### ISSUE TITLE
error on install

### ISSUE THREAD

**Issue by parsibox** [PAiC-BD/Extended-jSS7#2]
hi
i use java 1.7 and command mvn clean install 
it has this error 
what can i do?
how can i fix it? 
```
[ERROR] The build could not read 1 project -> [Help 1]
org.apache.maven.project.ProjectBuildingException: Some problems were encountered while processing the POMs:
[ERROR] Child module /home/mohsen/Extended-jSS7/sccp/sccp-api-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist @ 
[ERROR] Child module /home/mohsen/Extended-jSS7/sccp/sccp-impl-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist @ 
[ERROR] Child module /home/mohsen/Extended-jSS7/sccp/sccp-cli-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist @ 

	at org.apache.maven.project.DefaultProjectBuilder.build(DefaultProjectBuilder.java:363)
	at org.apache.maven.DefaultMaven.collectProjects(DefaultMaven.java:636)
	at org.apache.maven.DefaultMaven.getProjectsForMavenReactor(DefaultMaven.java:585)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:234)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:414)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:357)
[ERROR]   
[ERROR]   The project org.restcomm.protocols.ss7.sccp:sccp-parent:8.0.0-170 (/home/mohsen/Extended-jSS7/sccp/pom.xml) has 3 errors
[ERROR]     Child module /home/mohsen/Extended-jSS7/sccp/sccp-api-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist
[ERROR]     Child module /home/mohsen/Extended-jSS7/sccp/sccp-impl-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist
[ERROR]     Child module /home/mohsen/Extended-jSS7/sccp/sccp-cli-ext of /home/mohsen/Extended-jSS7/sccp/pom.xml does not exist
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException

```

**Comment by Ghostfacexx** [comment]
seriously? you cant change the name of the folders?

**Comment by parsibox** [comment]
change which folder name???

**Comment by Ghostfacexx** [comment]
the master pom looks for the child poms in ***-ext folders - just change
each folder to represent the correct location. and in the parent pom delete
the folders without the -ext! its 6 folders mention in the Parent - delete
the NON -ext ones. but thats the smallest issue. that stack is
UNCOMPILABLE. i tried more than 700 times.

**Comment by jarmex** [comment]
A similar repository can be found here [https://github.com/PAiC-BD-Sales/Extended-jSS7](https://github.com/PAiC-BD-Sales/Extended-jSS7) and it has more details on how to build the application.

**Comment by juankgardez** [comment]
Thanks!
